### ISSUE TITLE
[Bug]:  Nameplates No Longer Show In Third Person

### ISSUE THREAD

**Issue by Fewdys** [RequiDev/ReModCE#56]
Nameplates No Longer Show In Third Person

Edit: Also For Some Reason Some Animations That Use The Gesture Layer Are Also Broken (No Idea If This Is A VRChat Bug Or Not - For Now Im Gonna Assume It Is)

![image](https://user-images.githubusercontent.com/104469110/172214267-d405f85a-b226-44c1-807d-d38a0c5292d9.png)

**Comment by PuddingVR** [comment]
That was an intentional change that I contributed.

The third person camera is now based on the VR camera. This hides the mirror clone which fixes broken flickering lighting on your avatar in some worlds.
 
The whole UI is hidden (as you can see there is no double menu or mic icons).

Could maybe add an option to show the UI in third person but still fix the lighting.

As for gesture layer animations, it's probably a vrchat thing or a bad configuration (animations that aren't meant to go into gesture)
